//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nirajan_Books_shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_details
    {
        public int detail_id { get; set; }
        public int o_id { get; set; }
        public int p_id { get; set; }
        public int o_qty { get; set; }
        public decimal o_price { get; set; }
        public decimal o_total { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
